apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: {{ .Values.orders.servicePort }}
      targetPort: {{ .Values.orders.containerPort }}
  type: ClusterIP