apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: {{ .Values.users.image }}
          ports:
            - containerPort: 8000
