stages:
  - build

build_and_push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    # Build + push gateway
    - docker build -t arlg92/gateway-service:latest ./gateway
    - docker push arlg92/gateway-service:latest

    # Build + push users
    - docker build -t arlg92/users-service:latest ./users
    - docker push arlg92/users-service:latest

    # Build + push orders
    - docker build -t arlg92/orders-service:latest ./orders
    - docker push arlg92/orders-service:latest